version: '3.5'

services:
  angular-app:
    image: "mekniiemna/front_img"
    build: .
    container_name: angular-app
    ports:
      - '4200:80'
    volumes:
      - ./:/angular-app
    environment:
      - STYLE=css
